### ISSUE TITLE
Issues when installing using git

### ISSUE THREAD

**Issue by uhourri** [uhourri/ghmap#2]
After installing using :
`$ pip install git+https://github.com/uhourri/ghmap.git`

I get the following exception :
```
$ ghmap --raw-events raw-events --output-actions gh_all_actions.jsonl --output-activities gh_all_activities.jsonl
Traceback (most recent call last):
  File "/Users/hourri/ghmap-test/.venv/bin/ghmap", line 5, in <module>
    from ghmap.cli import main
  File "/Users/hourri/ghmap-test/.venv/lib/python3.13/site-packages/ghmap/cli.py", line 5, in <module>
    from .preprocess.event_processor import EventProcessor
ModuleNotFoundError: No module named 'ghmap.preprocess'
```

**Comment by uhourri** [comment]
@AlexandreDecan

**Comment by uhourri** [comment]
it works when changing the relative imports to absolute imports
@AlexandreDecan

**Comment by AlexandreDecan** [comment]
Don't use absolute imports as much as possible. I'll have a deeper look at this soon.

**Comment by AlexandreDecan** [comment]
Could you try by removing the two lines at https://github.com/uhourri/ghmap/blob/main/pyproject.toml#L30 : 
```
[tool.setuptools.packages.find]
include = ["ghmap"]
```

and replace them by 
```
[tool.setuptools]
packages = ["ghmap"]
```

It seems that `find` expects exact matches... I used it for a reason that is no longer valid, so the change should be fine.

**Comment by uhourri** [comment]
works perfectly

**Comment by AlexandreDecan** [comment]
Perfect! Sorry for the inconvenience. I'm not yet used with all the options and possibilities of the "new" pyproject.toml format.

**Comment by uhourri** [comment]
@AlexandreDecan I still get the same error when deleting [MANIFEST.in](https://github.com/uhourri/ghmap/blob/main/MANIFEST.in) file

**Comment by uhourri** [comment]
I fixed the issue by explicitly adding `ghmap.preprocess` and `ghmap.mapping` to **[tool.setuptools].packages** and specifying the full paths for the config files (`config/event_to_action.json` and `config/action_to_activity.json`) in **[tool.setuptools.package-data]**. Now it works fine without the MANIFEST.in file.

**Comment by AlexandreDecan** [comment]
The same error? Can you try in an isolated environment and confirm? This error shouldn't be related to the presence of the manifest file...Were there other changes? Le 11 déc. 2024 15:14, Youness Hourri ***@***.***> a écrit :
@AlexandreDecan I still get the same error when deleting MANIFEST.in file

**Comment by AlexandreDecan** [comment]
Ok, perfect!
